using StaticArrays
using RoboticsToolbox.HomogenousTransforms: Se2, Se3

println("=== SE(3) examples ===\n")

# ------------------------------------------------------------
# Example 1: Embed a manually constructed SE(2) (radians)
# ------------------------------------------------------------
println("Example 1: Manual SE(2) → SE(3) (radians)")

θ = pi/4
c = cos(θ)
s = sin(θ)

T2_manual = @SMatrix [
    c   -s   1.0
    s    c   2.0
    0.0  0.0  1.0
]

T3_1 = Se3(T2_manual)

println("T2 (SE2) =\n", T2_manual)
println("T3 (SE3) =\n", T3_1, "\n")


# ------------------------------------------------------------
# Example 2: Embed an identity SE(2)
# ------------------------------------------------------------
println("Example 2: Identity SE(2) → SE(3)")

T2_identity = @SMatrix [
    1.0  0.0  0.0
    0.0  1.0  0.0
    0.0  0.0  1.0
]

T3_2 = Se3(T2_identity)

println("T2 (SE2) =\n", T2_identity)
println("T3 (SE3) =\n", T3_2, "\n")


# ------------------------------------------------------------
# Example 3: Embed an SE(2) with pure translation
# ------------------------------------------------------------
println("Example 3: Pure translation in SE(2) → SE(3)")

T2_translation = @SMatrix [
    1.0  0.0  3.0
    0.0  1.0  4.0
    0.0  0.0  1.0
]

T3_3 = Se3(T2_translation)

println("T2 (SE2) =\n", T2_translation)
println("T3 (SE3) =\n", T3_3, "\n")


# ------------------------------------------------------------
# Example 4: Embed an SE(2) generated by Se2 (compatibility)
# ------------------------------------------------------------
println("Example 4: SE(2) generated by Se2 → SE(3)")

T2_from_Se2 = Se2(1.0, 2.0, 90.0; deg=true)
T3_4 = Se3(T2_from_Se2)

println("T2 (SE2) =\n", T2_from_Se2)
println("T3 (SE3) =\n", T3_4, "\n")
